name: Test minimal

on:
  workflow_call:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "build step"

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - run: echo "deploy step"
